services:
  server_api:
    container_name: server
    build: .
    ports:
      - '3001:3001'
    volumes:
      - .:/app
    environment:
      - DB_ENDPOINT=mongodb://mongodb_database:27017
    depends_on:
      - mongodb_database
    restart: always
  mongodb_database:
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - datamongodb:/data/db
volumes:
  datamongodb: